// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjxuzY0HyqDFaOJ8WoYOOgzhpZEE3ZfBg',
    appId: '1:676911405089:web:388217e97882c3f6b62b60',
    messagingSenderId: '676911405089',
    projectId: 'signin-example-b44f4',
    authDomain: 'signin-example-b44f4.firebaseapp.com',
    storageBucket: 'signin-example-b44f4.appspot.com',
    measurementId: 'G-0JTQYMEJGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApn3wuhqkB1SYxAWKJNhozi4ilA90Bn1I',
    appId: '1:676911405089:android:1597229510207f32b62b60',
    messagingSenderId: '676911405089',
    projectId: 'signin-example-b44f4',
    storageBucket: 'signin-example-b44f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA67lvWhQSm-Dj_IdqvLg3eAmBGHTk6F4I',
    appId: '1:676911405089:ios:29a80fccd5c2c365b62b60',
    messagingSenderId: '676911405089',
    projectId: 'signin-example-b44f4',
    storageBucket: 'signin-example-b44f4.appspot.com',
    iosBundleId: 'com.example.firebaseSignin',
  );
}
